name: Documentation

on:
  push:
    branches: [main]
    paths:
      - '**.md'
      - 'src/**'
      - 'docs/**'
      - 'playground.html'
      - 'docs.html'
      - 'typedoc.json'
      - 'dist/browser/**'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build project
        run: npm run build
      
      - name: Generate TypeDoc documentation
        run: npm run docs
      
      - name: Add playground and browser bundle to docs
        run: |
          # Copy playground to docs directory (alongside TypeDoc docs)
          cp playground.html docs/playground.html
          
          # Copy browser bundle to docs
          mkdir -p docs/dist/browser
          cp -r dist/browser/* docs/dist/browser/ || echo "Browser bundle not found"
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          enable_jekyll: false